import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { NextIntlClientProvider } from "next-intl";
import {} from 'next-intl';
import "./globals.css";
import { getLocale } from "next-intl/server";
import { SpeedInsights } from "@vercel/speed-insights/next"


export const metadata: Metadata = {
  title: {
    default: "Papirus",
    template: "%s | Papirus",
  },
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const locale = await getLocale()
  const messages = (await import(`../messages/${locale}.json`)).default;
  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${inter.className} text-text-dark dark:text-text-light`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
            <ThemeProvider
              attribute="class"
              enableSystem={true}
              defaultTheme="system"
            >
              {children}
            </ThemeProvider>
        </NextIntlClientProvider>
        <SpeedInsights/>
      </body>
    </html>
  );
}
